### ISSUE TITLE
zabbix_sender [497947]: option requires an argument -- o

### ISSUE THREAD

**Issue by zaheerabbas1988** [objectiveit/zabbix-ssllabs#3]
` /usr/lib/zabbix/externalscripts/ssllabs_checker.sh example.com`
returning the following error:

`zabbix_sender [497947]: option requires an argument -- o`

# Configuration

Here is my modified scrip:

`#!/bin/bash
ZABBIX_SENDER="/usr/bin/zabbix_sender"
ZABBIX_CONFIG="/etc/zabbix/zabbix_agentd.conf"
#ZABBIX_CONFIG=""
ZABBIX_SERVER="127.0.0.1"
ZABBIX_PORT="10051"
ZABBIX_KEY="ssllabs.certificate.grade"

SSLLAB_SCAN="/usr/lib/zabbix/externalscripts/ssllabs-scan"
SSLLAB_OPTIONS="-quiet -grade"

set -o errexit
ZABBIX_SENDER_CMD=$ZABBIX_SENDER
if [ -z $ZABBIX_CONFIG ]
then
    ZABBIX_SENDER_CMD="$ZABBIX_SENDER_CMD -z $ZABBIX_SERVER -p $ZABBIX_PORT "
else
    ZABBIX_SENDER_CMD="$ZABBIX_SENDER_CMD -c $ZABBIX_CONFIG "
fi

HOST=$1

IFS=':' read -r -a RESULT_GRADE <<< `$SSLLAB_SCAN $SSLLAB_OPTIONS -hostcheck $HOST`
#IFS=':' read -r -a RESULT_GRADE <<< `echo '"www.ssllabs.com" : "F"'`
VALUE=$(echo -e ${RESULT_GRADE[1]} | sed -e 's/[:space:"]//g')
ZABBIX_SENDER_CMD="$ZABBIX_SENDER_CMD -s $HOST -k $ZABBIX_KEY -o $VALUE"
$ZABBIX_SENDER_CMD 1>/dev/null`

Any help with this will be really appreciated. Thank you

**Comment by stfast** [comment]
I have solved this, here are my script modifications:

diff  /etc/zabbix/externalscripts/ssllabs_checker.sh  /etc/zabbix/externalscripts/ssllabs_checker.sh.original 

< ZABBIX_CONFIG="/etc/zabbix/zabbix_server.conf"
> ZABBIX_CONFIG="/etc/zabbix/zabbix_agentd.conf"

< SSLLAB_SCAN="/usr/local/bin/ssllabs-scan"
< SSLLAB_OPTIONS="-quiet -grade -usecache"
> SSLLAB_SCAN="/opt/zabbix_scripts/ssllabs-scan"
> SSLLAB_OPTIONS="-quiet -grade"

< VALUE=$(echo -e ${RESULT_GRADE[1]} | sed -e 's/[:space:"]//g') | cut -d "\\\\" -f2
< ZABBIX_SENDER_CMD="$ZABBIX_SENDER_CMD -s $HOST -k $ZABBIX_KEY -o \\"$VALUE\\""
> VALUE=$(echo -e ${RESULT_GRADE[1]} | sed -e 's/[:space:"]//g')
> ZABBIX_SENDER_CMD="$ZABBIX_SENDER_CMD -s $HOST -k $ZABBIX_KEY -o $VALUE"

**Comment by stfast** [comment]
Than again, I rewrite it with jQuery grade parsing:

#!/bin/bash

HOST=$1

\# Configuration
ZABBIX_SENDER="/usr/bin/zabbix_sender"
ZABBIX_SERVER="127.0.0.1"
ZABBIX_PORT="10051"
ZABBIX_KEY="ssllabs.certificate.grade"

SSLLAB_SCAN="/usr/local/bin/ssllabs-scan"
SSLLAB_OPTIONS="-quiet -usecache"


\# Do the job
set -o errexit

GRADE_VALUE=`$SSLLAB_SCAN $SSLLAB_OPTIONS -hostcheck $HOST | jq '.[] | .endpoints|.[0] |.grade' | sed 's/\"//g'`
\#echo $GRADE_VALUE

ZABBIX_SENDER_CMD="$ZABBIX_SENDER_CMD $ZABBIX_SENDER -z $ZABBIX_SERVER -p $ZABBIX_PORT --host $HOST -k $ZABBIX_KEY -o $GRADE_VALUE"
\#echo "$ZABBIX_SENDER_CMD"

$ZABBIX_SENDER_CMD 1>/dev/null
